### ISSUE TITLE
Better Injection Support / Support for Services

### ISSUE THREAD

**Issue by noobxgockel** [junkdog/artemis-odb#258]
Well Hello!
I am currently programming my own little game with libgdx + artemis odb.

I found it rather disturbing that there is no real good Method to autoinject classes that have nothing to do with the whole Entities and World thing.
Workaround is to use a Manager and forbid to use world related stuff, but thats rather hard to enforce.

My Suggestion would be either to simplify the Injection and registration for third party Injection or to add a "Service" class. Basically only containing initialize and process Method. Those would have native injection Support tho.

Why do i think i need such thing ?
Some things arent supposed to or shouldnt by convention be put into ECS.
The Assets, camera, maps are a few examples of such.

Just my 2 cents about that topic. If the feature is wanted i could try and ramp up a pull request.

**Comment by junkdog** [comment]
Hi! You can [inject arbitrary classes](https://github.com/junkdog/artemis-odb/wiki/%40Wire#injecting-non-artemis-dependencies). If you want to *inject into* a non-artemis type, call [World#inject](https://github.com/junkdog/artemis-odb/blob/12816c4fed206dfd404be6cd30e66261a1650944/artemis/src/main/java/com/artemis/World.java#L185) ([this is what EntityFactories do](https://github.com/junkdog/artemis-odb/blob/master/artemis/src/test/java/com/artemis/reference/ShipImpl.java), in order to avoid a bit of boilerplate).

Does this cover your use case(s)?

**Comment by noobxgockel** [comment]
Yes it does, but im wondering why arbitrary classes are handled so much differernt at Registration than Systems or Manager ?
Systems and Managers can be added while or after instanciating the World. Why cant you do the same with arbitrary classes.

My particular "wish" is to come to an uniform, register(Anything) or set(Anything).

Thanks for quick response,
~ Markus

**Comment by junkdog** [comment]
> Yes it does, but i'm wondering why arbitrary classes are handled so much differernt at Registration than Systems or Manager ?

Well, all artemis types are implicitly eligible for injection. With native artemis types we can make a lot of assumptions that don't really apply to non-artemis types; which subclasses to look for, knowing there's only ever one instance per type, special handling for ComponentMappers etc.

Conceptually, the DI mechanism is meant to only run once per world setup/initialization. If there's a compelling use case for changing that behavior, I'd reevaluate a change of behavior (post 1.0.0 though)/

> Systems and Managers can be added while or after instanciating the World. Why cant i do the same with arbitrary classes.

Systems can no longer be added after a world has been initialized. Since 0.8.0 (or maybe 0.7.0), I think there's a potential bug with entities potentially not being inserted into systems that were added after calling World#initialize.

> My particular "wish" is to come to an uniform, register(Anything) or set(Anything).

Aside from only being registered at World creation, isn't that was `#register` does? How would `#set` work?

**Comment by ollipekka** [comment]
I think #register goes pretty far for your typical needs. I'd avoid providing injecting services, because injecting runtime could be a possible performance pitfall AND the implementation would create complexity to the library (and for what use case?). 

Unless of course someone figures out simple and fast way to inject stuff at runtime..

**Comment by junkdog** [comment]
> I think #register goes pretty far for your typical needs. I'd avoid providing injecting services, because injecting runtime could be a possible performance pitfall AND the implementation would create complexity to the library (and for what use case?).

:+1: 

> Unless of course someone figures out simple and fast way to inject stuff at runtime..

Well, there are potential [alternatives](https://github.com/junkdog/agrotera) (also code generation via annotation-processors, bytecode injection, and the java compiler API), but not without complicating project setup or limiting platform support (damned be android and GWT).

I'm currently working on de/serialization support for the upcoming release - it's a real pain getting something to work against all backends without resorting to something that explodes memory usage or implodes performance. I like java (and the JVM), but sometimes its [limitations really gets on my nerves](https://twitter.com/junkdogAP/status/582815614059868160).

**Comment by noobxgockel** [comment]
Just to clarify my last statements, i created a gist: https://gist.github.com/noobxgockel/bbbce4a3f8ee497a4145

And ollipekka is right somewhat, i have only thought of implementing the arbitrary object injection just the way it is currently: Every injectable object has an identifier, if no identifier is passed to the method, the classname is used instead.
I think that it would benefit from beeing uniform throughout as explained in the gist above.

Im not good at waging pro and cons of my suggestion. It probably really hasnt many use cases and im not aware of the potential performance dangers of injection.

**Comment by junkdog** [comment]
Just about to hit the sack (this whole summertime switch while making an extra effort to get to work in time has left in broken state), but I'll return tomorrow ;)

:sleeping:

**Comment by junkdog** [comment]
Hmm, problem, as I see it, is that your suggestion seems to shift the POV to an injection-centric one. `World#setSystem` and `World#setManager` express a clear intent in how they interact with the framework. Arbitrary objects otoh are only processed by artemis insofar that they might be injected (and they still require [special handling](https://github.com/junkdog/artemis-odb/wiki/%40Wire#by-type)).

There's a tendency to embed the artemis type in the class name (PositionUpdateSystem, SpriteResolverManager etc - I do it myself) - collapsing register/setManager/setSystem into a single method would reinforce this trend.

I actually want to shift some responsibility from World to WorldConfiguration - forgetting to call `World#initialize` happens too many times (there are now several checks in World, asserting that the instance has/has not been initialized, unnecessarily bloating the code).

If setSystem/setManager were moved to `WorldConfiguration`, `World#initialize` could be completely removed.

**Comment by noobxgockel** [comment]
Yeah, injection is awesome and i want to use it without getting heavy 3rd party dependicies. The Special Handling (by type) is the exact same as injecting Systems and Managers, i like that very much.

I made a lot of small unreleased Prototypes and never forgot to initialize the World. And the first place i would look if i got wierd errors would be the main class. The time saved on that one might not be huge on that one, but if it cleans up code, why not ^^

I like the idea of shifting everything into WorldConfiguration with a single register Method, nicely organized with a good Hint on whats possible with the Framework :+1:

**Comment by junkdog** [comment]
> I made a lot of small unreleased Prototypes and never forgot to initialize the World.

Yeah, it doesn't happen all the time, but I've tried to remove all errors resulting from forgetting to call a method; objects in an intermediate state are best avoided... And then I made Entity a flyweight instance when processing entities = huge pain (I need to fix that somehow, or I'll settle for being a hypocrite with good intentions).

> I like the idea of shifting everything into WorldConfiguration with a single register Method

Sorry, probably not going to happen - but I'll leave the class extensible, so if you want to extend WorldConfiguration and overload #register, go for it!

**Comment by DaanVanYperen** [comment]
Answered, no actions (?), closing.
