### ISSUE TITLE
Aspect is ignored if entity components are changed by both edit method and transmuter

### ISSUE THREAD

**Issue by kotcrab** [junkdog/artemis-odb#268]
I found an issue when Aspect for system is ignored. This happens after adding entity component using `edit()` method and then using transmuter on it. See this sscce: http://pastebin.com/sSNi32YR, output:
```
test.ArtemisTest$BarComponent@254989ff
null
null
...
```

Null should never be printed because entities processed by TestSystem must have BarComponent.

However if transmuter is used first and then `edit()` is called then everything works as expected.

I know that I can add components using transmuter, I just found this issue by accident so I'm reporting it. Tested on 0.9.1-SNAPSHOT.

**Comment by junkdog** [comment]
Thanks for reporting! I ran into this issue myself last week, but I wasn't sure whether it was fixed in the snapshot or not. It was too hot for getting anything done during the weekend; it's overdue, but expect a release soon - entity de/serialization has been pushed back to 0.11.0 - so it's mostly bug fixing remaining.

**Comment by junkdog** [comment]
This bug affects EntityFactories in conjunction with edit() too.

**Comment by Namek** [comment]
We've seen the same bug with transmuters a week ago in our small proejct. But we didn't know how to reproduce it. Thanks @kotcrab
