### ISSUE TITLE
(Extend API for) Entity DSL, OnReplace & Pooling

### ISSUE THREAD

**Issue by gjroelofs** [junkdog/artemis-odb#348]
This issue comprises 2 aspects:
- Code generation surrounding syntax to easily access and operate on Components given an Entity.
- The introduction of "onReplace" entity subscription semantic.
## Why?

The combination of syntax which provides easy access to mutation of an entity, "onReplace" subscription and pooling of components will allow a coding style similar to Functional Reactive Programming. It will also allow a faux-immutable style of programming while allowing the coder to sidestep the performance overhead of this style when needed.

Concretely the following advantages:
- **Easy to read syntax for Entity mutation and Component access.**  
  _The structure of the code could be Entity#add<X>(args for X) / remove<X>() / replace<X>(args for X) / get<X>_

E.g.: Given a Health and Mana component, both accepting a float value.

``` Java
Entity e = world.createWorld();
e.addHealth(10)
  .addMana(10);

e.replaceMana(20);

e.removeMana();

Mana manaComponent = e.getMana();
```
- **Allow tracking of a Component state with a delta.**  
  _Code that normally needs to use polling to update on state changes, or handwritten events, can now respond to conditional state changes._

``` Java
// Keep track of a parent / child relationship. Where Parent & Child are both components containing an Entity variable named "value". 
world.onComponentChange(Parent.class, (e, oldParent, newParent) => {
     newParent.value.addChild(e);
});
```
- **Pooling of Components hidden behind the general syntax**  
  _The add<X> / remove<X> / replace<X> syntax will query pools before instantiating new Components._
## How?

One approach could be to use a code generation library which allows proper parsing of Java code which supports Maven & Gradle integration. And example of such a framework: http://spoon.gforge.inria.fr/examples.html

The basic strategy for code generation could be:
- Gather all Components used in the project, and order on how many Worlds they are used in, then generate a unique ID per Component.
- Expose the logic in Artemis for the package which allows direct mutation of an Entity given a Component and family index. 
- Generate a class with an internal Pool per Component, along with the add<X> / remove<X> / replace<X> logic delegating to the Pool for instantiation. Add<X> and Replace<X>, accept all public variables in X and fill the newly acquired Component from the Pool. 
### Side Effects
- By introducing the Entity shorthand syntax and factoring out ComponentMapper/ComponentType we allow the use of performant code in situations where ComponentMapper cannot be used.
  E.g.: Data-driven functions which operate on an Entity.
- _(Added 13/9/'15)_ If we know the Components to be used at compile time we can optimize ComponentManager.
## Constraints
- Users which do not use the code-generation should be able to use Artemis as-is.
## Problems
- To factor out the ComponentMapper syntax in the code generated for the Entity syntax, we need to know which Components are used in which Worlds.
- The faux-immutable style of coding could lead to problems in multithreading. In particular the semantics of replaceComponent needs to be well defined.

**Comment by DaanVanYperen** [comment]
Some observations.
- To keep API simple, drop the distinction between `add` or `replace`, the distinction is an artifact of old `ComponentMapper`s, and just leads to extra typing. instead provide a `hasHealth()` for those cases the developer needs to check for a pre-existing component.
- Can we draft up some more common cases: `Vector2` pos, `Color`, or a Physics component with multiple vectors, empty tagging component.
- State changes should include component creation/destruction. 
- I'd like some clarity when listeners are triggered, probably best to do it in between systems instead of immediately to avoid unpredictable world state on receiving end.
- Incorporation of plucking user defined setters from components.
- Resolving Library provided components.
- IDE support should be solid to make it a core feature. Probably best to first make it a plugin and open up API in core where needed. As `Entity` wrapper (`CompositeMapper` or `ExtendedFlyweight` or some such).
- Multi world support. Consider cases where you have client/server with naming collisions due to different implementations for each side could cause awkward bugs. 
- For core feature goal should be to bring zero configuration auto-complete in all common IDEs without having to build a maven/gradle target explicitly.
- @Junkdog Interested to hear what the replacement mechanic will do to performance regarding fetching and caching.

**Comment by gjroelofs** [comment]
My comments, the points I do not comment on I agree with in general.

- Can we draft up some more common cases: Vector2 pos, Color, or a Physics component with multiple vectors, empty tagging component.
*For empty tagging component we could follow the Entitas structure, in which empty/tagging components resolve to a boolean on the Entity. E.g.: e.isMovable()*

- State changes should include component creation/destruction.
*Could you give some examples of this? These should be covered by Add & Remove Subscription listeners already provided. Or do you mean triggers on creation/destruction from Pool?*

- IDE support should be solid to make it a core feature. Probably best to first make it a plugin and open up API in core where needed. As Entity wrapper (CompositeMapper or ExtendedFlyweight or some such).
*and*
- For core feature goal should be to bring zero configuration auto-complete in all common IDEs without having to build a maven/gradle target explicitly.
*First-class IDE support would require plugins written for those IDE's if we do not rely on Maven/Gradle. I think using well-defined build systems will be preferable over plugins we need to maintain.*

- Multi world support. Consider cases where you have client/server with naming collisions due to different implementations for each side could cause awkward bugs.
*I would separate Multi-world support from client/server implementations with differing implementations as they address different problems. *

**Comment by DaanVanYperen** [comment]
> State changes should include component creation/destruction.
> Could you give some examples of this? These should be covered by Add & Remove Subscription listeners already provided. Or do you mean triggers on creation/destruction from Pool?

Just making it explicit, couldn't tell if the listeners will trigger in cases of a newly added component (and primary use case) upon removal from an entity.

> and
? :D

> I think using well-defined build systems will be preferable over plugins we need to maintain.
I agree, the convenience/utility drops a lot though if we can't have auto completion work out of the box. At least for my jam use cases .;)

**Comment by Namek** [comment]
About syntax: what about https://github.com/junkdog/artemis-odb/wiki/EntityFactory ? Isn't extending this just enough?

**Comment by junkdog** [comment]
We'd need to have component deltas opt-in, not affecting overhead when not in use. Feels like the most straightforward way would be to wrap entityId in another generated class, the "EntityWithComponentMethods". Most methods which take Entity as a parameter already have int overloads).

Refactoring component storage is more problematic though.

@Namek EntityFactories are too verbose and are problematic to set up.

**Comment by gjroelofs** [comment]
@DaanVanYperen

I'm suggesting to generate a class in a task/precompile step that needs to run after changes to components. Autocompletion and the like works because of the generated class which is available after the task is run. (which ideally would be linked into an IDE trigger) 

The "and"  was meant to describe I would address the issue with the following answer :) 

@Namek, @junkdog
I see two options:
- **Shadow Entity.java in the consuming project**  
  The major downside here is the *hackish* nature; I've also found that some more advanced techniques (xtend macros) did not like the shadowing if compiled *with* the artemis dependency (which is solveable). The upside is having the methods directly on Entity.
- **Generate an EntityDSL class either with static methods accepting Entity or as a builder pattern**
   Cleaner, but added overhead (syntax or builder creation) . However, in some languages (Xtend) / Java extensions (Lombok with @ExtensionMethod) you can then use the class as an extension source.

@junkdog

Could you detail the refactoring required for component storage a bit?

**Comment by gjroelofs** [comment]
@junkdog

I'm a bit confused on the wrapping of entityId. 
My line of thought was to generate the componentID, and bypass ComponentMappers.

**Comment by gjroelofs** [comment]
After some work with Spoon; the naive implementation only scans the code in the current project.
I'm now looking whether it can be configured to look into dependencies as well.

## Easy Route: Manual specification

Looking at it from a different perspective:
To implement proper component ID generation we would need some mechanism that shows which Components are used by which World. If this is mechanism is written manually in the consuming project we can catch all Components there. The obvious downside being that you need to manually specify which components will be used by the World.

@junkdog 

### Food for thought

The constraint that the number of Components is not known at instantiation of the World leads to *some slight* overhead (ComponentManager; bound checking, expanding Bag). What we could do is create a common interface for the current ComponentManager, extend it and create one that uses integrates the fact that we know which Components are used at instantiation.

## Hard Route: Search

Most uses cases for a World have a single instantiation location where all Systems etc are added.
We could go on a recursive search through all used systems and their dependencies to find which Components are (in)directly used by a World.

**Comment by gjroelofs** [comment]
Alternatively, we can use the concept of a Class that contains all known ComponentMappers which are instantiated lazily per World. 

The EntityDSL builder implementation could lookup and delegate to this class upon instantiation. (Or hide the ComponentMappers internally)

**Comment by junkdog** [comment]
Ok, a bit more awake today (tried to process this yesterday - and other things, but I was beyond salvation).

> I'm suggesting to generate a class in a task/precompile step that needs to run after changes to components. Autocompletion and the like works because of the generated class which is available after the task is run. (which ideally would be linked into an IDE trigger) 

Refactoring would break without IDE integration however. It could be added as a later step, but I think that at least intellij should support it (from my understanding, intellij plugings are vastly more easy to write compared to eclipse plugins, and eclipse's popularity is fading).

If only we had roslyn on the JVM and plural IDE side... I thought truffle/graal was going to be something towards that end, but it's not as far as I understand it(?).

> Could you detail the refactoring required for component storage a bit? 

I missed the constraints part ("Users which do not use the code-generation should be able to use Artemis as-is."). I was mostly thinking about saving the previous component state; it kinda lends itself to "double buffering"  of two arrays (ByteBuffers or such) per component type. *But then I started thinking about `References to components` so disregard my remark).

> Most uses cases for a World have a single instantiation location where all Systems etc are added.
We could go on a recursive search through all used systems and their dependencies to find which Components are (in)directly used by a World.

[ecs-matrix](https://github.com/junkdog/ecs-matrix) already scans for artemis types. It'd need to be extended to scan dependencies too though.

> Shadow Entity.java in the consuming project

It's more hackish, but I think brevity wins - there's no way around it being invasive somehow; since it's opt-in and with an eye on readability, shadowing Entity means less noise in project code.

## References to components

Stashing away references to components is disallowed, if we're replacing and keeping previous component state? https://github.com/junkdog/artemis-odb/issues/269 could guard against storing actual components in bag, arrays etc, but dealing with storing a reference to a field is much trickier:

```java
public class Position extends Component {
	// user might want to retain xy elsewhere
	public Vector2 xy = new Vector2();
}
```

We could use the same instance for the component though; copy the actual instance's data to the previousState instance.

**Comment by DaanVanYperen** [comment]
I'm a big proponent of introducing better state change events, love that in core. The composite mapper/mixin entity precompilation however is something that is pretty fundamental pivot in how the framework operates. IF it's optional it does not belong in core imo.

> I'm suggesting to generate a class in a task/precompile step that needs to run after changes to components. Autocompletion and the like works because of the generated class which is available after the task is run. (which ideally would be linked into an IDE trigger)

Understood. This does shift us further towards the brittle end of the spectrum and I fear the paradigm shift would cause some distrust in the typical user if we put it in core. It would be a good plugin for users who explicitly choose to offset the unavoidable IDE glitches in exchange for the speedup on the other end.

There's a lot of dials and knobs being added to odb causing the exposed api to grow immensely and making it harder and harder understand and maintain. DSL vs rainbow flavors of JSON vs Factories vs Editors vs Proxies vs Archetypes vs code generation. Before this implementation specific discussion we need to set out some clear goals for core and what we want to consolidate/replace/externalize.

**Comment by DaanVanYperen** [comment]
Perhaps we can steer this discussion towards opening up the API to allow more invasive richer plugins and deal with that how we deal with all the contrib stuff; if it gets popular enough we can pull it into core.

**Comment by gjroelofs** [comment]
I'm also a fan of keeping core light, and introducing this in a plugin.

The added benefit of shadowing Entity.java is that we can keep the API we
need to access protected, without exposing it. (Or we could just generate
into "com.artemis")

I was actually surprised that serialization and the like was introduced
into core.
From our end we see that a generalized serialization implementation tends
to run into those special cases which need proper serialization either way.
(Or we don't serialize the World; but a parameters object that sets it up.
Most of the time we are dealing with hidden state (UI etc) that Entity
serialization doesn't handle)

I already discussed my thoughts on streamlining general design with Junkdog
and am in favor of opening the discussion on that.
(Although I'm also skeptical of the practicality of it.)

*Gijs-Jan Roelofs*

*CodePoKE  -  **AI Consultation, Software Development & Game Design*

*Tel: +31 (0)6-45132283*
*VAT: 1938.99.388B02*
*Address: Maasboulevard 1, Maastricht, 6211 JW, Netherlands*

**Comment by junkdog** [comment]
>  I was actually surprised that serialization and the like was introduced into core.

Corner-ish case, but it's a useful USP + helps establish some measure of "idiomatic artemis"; in this case - *Resolver managers which allocate transient components from asset reference components.

> Most of the time we are dealing with hidden state (UI etc) that Entity serialization doesn't handle)

You can extend SaveFileFormat and add pojo:s holding additional data (or write serializers for systems). It does kinda assume that World is central to the overall design though.

> (Although I'm also skeptical of the practicality of it.)

Skeptics rojoice!

**Comment by gjroelofs** [comment]
> Corner-ish case, but it's a useful USP + helps establish some measure of "idiomatic artemis"; in this case - *Resolver managers which allocate transient components from asset reference components.

I can get behind that; one of the first decisions in our framework was the introduction of AssetReferences and it's a concept not that many devs use while it can alleviate a lot of headaches. (even not in ECS)

> You can extend SaveFileFormat and add pojo:s holding additional data (or write serializers for systems). It does kinda assume that World is central to the overall design though.

We found that in a lot of use cases we didn't need to serialize the entire world and primarily on focused on well-defined entry points that act as both initialization and reset. Starting a level and loading a level are the same thing; which removes some of the boiler plate that normally needs to be written if you serialize the entire world state (i.e.: your save file format isn't easily setup from code 

(Although I'm also skeptical of the practicality of it.)
Skeptics rojoice!

**Comment by junkdog** [comment]
> We found that in a lot of use cases we didn't need to serialize the entire world and primarily on focused on well-defined entry points that act as both initialization and reset.

Hmm, I think our goals converge, but approach/implementation differs. I tend to serialize quite frequently and in different contexts, and it's pretty much a unified approach.

Since loading is additive, we use three serialized states/save in our current project:
- theme: basically the entire level, limited to all the static stuff basically
- dynamic: this includes anything which moves/scales/etc and any ephemeral entities
- save: player state and metadata - normal SaveFileFormat extended with a pojo. doesn't serialize any entities (atm).

_theme_ is pretty much RO, _dynamic_ and _save_ are... saved. The only custom code we use is populating the state pojo.

Our Prefab class just wraps a tiny save (1-10 entities).

Current game has the editor is built straight into the game; so any dangerous operations record a snapshot of the world prior to executing, in case of failure, the `FailsafeInvocationStrategy` rolls back until it finds a working state (meaning, world.process() doesn't throw). (I took the idea from unity actually, but multiple states instead of just pause-play + recoverability).

There's some overhead involved with keeping the world always serializable, but it's usually pretty easy to fix. I do think it helps in uncovering bugs too, save-load is bound to venture into some unforeseen code paths with a shady state.

> Do you mean that you would open the discussion up for things such as Entity -> Group -> System, and listeners at each level?

Each level? Crazy talk!

I'm starting to think that this is really two different tasks: code gen and jacking in more granular listeners.

It'd be interesting to experiment with code gen, but in the end, I don't think we can provide an easy-to-use/easy-to-setup solution. Brittleness is another thing I worry about. Xtend feels like the overall easiest approach.

Listeners are probably more feasible. Could open up ComponentManager a bit I suppose, bnt it's something of a pandora's box. It might be the equivalent of sun.misc classes, though they're pretty stable atm. Requires some tinkering before it becomes clear what needs to be opened up.

Component deltas is probably the biggest challenge, and how it affects performance.

~~Per-component pools, wouldn't that interfere with multi-world scenarios, or pay the lookup cost? Unless it's a world-bound poolId.~~ (nvm)


> The faux-immutable style of coding could lead to problems in multithreading

artemis-odb will most likely never be multithreaded; it'd require profiling/introspective tooling to trace why code runs 3 times slower with 8 cores.

**Comment by gjroelofs** [comment]
I've dug a bit further in Spoon vs. Xtend:

+ Spoon only discovers those Types properly in the sourcepath. Combining Spoon with [Reflections](https://github.com/ronmamo/reflections) we can discover also those types in the classpath.
- Spoon only works if the project compiles. Xtend allows parsing of the AST and even works on partially compiling classes (I tested this with my Mappers implementation).

*For the Entity DSL approach:*
An approach which completely sidesteps hacking with component IDs is to generate an Entity which has stubs for the various add/replace/remove methods; which are then overloaded by a world-specific Entity. This class then has static ComponentMappers to which the methods delegate.
A specific EntityManager which instantiates these specific Entities are then generated and used by each world.

**Comment by gjroelofs** [comment]
Approach:

- Overload Entity.java, add in methods for add/remove/replace/get methods for found components in CompilationUnit.  Default policy delegates to pre-existing Entity methods so as to ensure that a baseline works when the specialization which delegates to ComponentMappers fails.
- Extend Entity per World with overrides for the component methods which delegate to static ComponentMapper fields.
- Extend RecyclingEntityFactory such that it now creates the specialized Entity.
- Extend EntityManager such that it instantiates the specialized REF, and upon initialization injects all Mappers into the static fields in the specialized Entity.
- Instantiate World with the specialized EntityManager.

Alterations:
- Introduction of EntityManager in WorldConfiguration
- Remove final from EntityManager, Entity, RecyclingEntityFactory, expose for extension.

Problem:
- Systems depend on Entity.flyweight(), which instantiates the wrong Entity type.

**Comment by DaanVanYperen** [comment]
@junkdog think we should strive to get contract changes into 1.0.0 release, specifically for:

> Systems depend on Entity.flyweight(), which instantiates the wrong Entity type.

by moving it to EntityManager, and perhaps (performance cost?)

> Introduction of EntityManager in WorldConfiguration
> Remove final from EntityManager, Entity, RecyclingEntityFactory, expose for extension.

**Comment by gjroelofs** [comment]
At the moment the implementation delegates to ComponentMapper.
I want to look into inlining the contents of ComponentMapper based on the type required to address the component in question. (information that is already available during compile)

**Comment by DaanVanYperen** [comment]
API changes are in, pop a new ticket if you need any more changes on odb side!

**Comment by gjroelofs** [comment]
Generation hook strategies that are possible:

Ideal #3: Java Parser that parses all .java files, generate Xtend Annotation that hooks into #1
	
		#1 Xtend Annotation: predefine the components that need to be generated, generate Xtend, delegate to 
							Xtend compiler which generates Java.
			+ Code doesn't need to be in compiling state.
			+ Plugin clean as it uses Xtend API
			- Xtend class shadowing does not work yet*
			- Xtend class define required
			- Manually define which Components to use
			
		#2 Xtend Annotation: predefine the components that need to be generated, generate Java
			+ Code doesn't need to be in compiling state.
			- Xtend class define required
			- Plugin code could be messy
			- Manually define which Components to use
			
		#3 Java Parser scan for Annotation, generate Xtend that hooks into #1.
			+ Code doesn't need to be in compiling state. (? if we get Java AST to work)
			- Manually define which Components to use
			
		#4 Build plugin that generates code after compilation.
			- Doesn't work if code isn't compiling
			+ No manual definition of components

**Comment by DaanVanYperen** [comment]
4 is definitely less cool but sounds less fragile. How was your experience playing around with xtend?

As it relates to this discussion, as a roadmap for 1.0.0 we've settled on the following future for the pre-existing component related API.
- ComponentMapper - Promote in docu as go-to for accessing/mutating.
- EntityFactory, EntityBuilder - Discourage in near future deprecate or refactor depending on DSL viability.
- Archetype, EntityEdit, Transmuter - Support for 1.x.x at least but move to background as low level niche API.

So all in all, we're still looking for a concise way of assembling entities.  ComponentMapper is too verbose. Same with EntityEdit, EntityBuilder isn't pooling compatible, 

Factories might work if we make them a bit more flexible and transparent. Still, @junkdog found the annotation processor to flake a bit, so can't say our path is clear.

**Comment by gjroelofs** [comment]
Fair enough. The Xtend compilation cycle worked quite well if it weren't for the overloading issue (which I've noted upstream and won't be addressed until the next release).

Everything works so far if I stick to Xtend.

It's actually far less fragile due to it working if the project doesn't compile; but yeah.

**Comment by DaanVanYperen** [comment]
Didn't mean to imply DSL can't fill that hole, it might.

wouldn't consider a build step that doesn't run due to a previous build step failing fragile, just having a predictable drawback

Then again, read 'build plugin' as a maven/gradle plugin that is manually run, your reply implies something broader.

**Comment by junkdog** [comment]
(this one stays as a historical document)

/housekeeping

**Comment by DaanVanYperen** [comment]
Putting historical documents in the freezer to help out grooming.
