### ISSUE TITLE
user-instantiated ComponentMappers blow up when entityId > 63

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#477]
this impacts custom mapper implementations

**Comment by DaanVanYperen** [comment]
Started writing a test but `ComponentManager` encapsulates part of the component mapper life-cycle. The > 63 error seems to be what happens when just instancing `MyComponentMapper` class without extending the ComponentMapper (currently not possible), so the mapper is never really properly hooked up.

We could open up `ComponentManager` for extension, but why not create (suggest) a proxy implementation? See `M.java` in contrib, it's pretty clean and non-invasive.

Let me know what your intention is here @junkdog.

**Comment by DaanVanYperen** [comment]
Workaround available.
