### ISSUE TITLE
Question: Coupling Artemis with GUI

### ISSUE THREAD

**Issue by ReneHabermann** [junkdog/artemis-odb#490]
Hi,
sorry if this is the wrong place for the question, i didn't find anything else that seemed appropriate. I'd really like to use artemis for my game and i'm currently rebuilding it with it, struggling at some parts that were very easy before.

The core problem is this: **I do know that a i created an interesting entity, but my AspectSubscription can't find them, only at some point in the future when i can't easily trigger the appropriate reaction anymore.**

Simple example:
I have a set of entities that i want to display in the GUI as a list. I can identify the entities via a common aspect. I can add and delete entities of this type via the GUI. The current GUI Screen is no System itself, but has a reference to World. So far so presumably simple.
If this matters, i'm using scene2d and only want to update my GUI a single time on the change.

What i can't seem to figure out is how or when to update the GUI on addition or deletion of an entity.
In general, i get those entities via the appropriate aspect subscription.
I tried
1. Update the entity list after creating a new entity - does not work because the AspecSubscription does not find the entity. I guess because it doesn't have the component yet (didn't find any doc on the lifecycle).
2. Add a subscription listener, that gets notified about the new entity. Did not work for me either - i do know what entity was added, but calling the general method that builds this GUI part fails too, since the AspectSubscription still does not find the entity. I guess the component is added just after this.

Using approach 2 i would still need to have 2 methods - one for reacting to changes in the entities and one for building the list when initially entering the screen (i do have to add the existing entities here, no change happening). This was very easily done before, just always refreshing the list when appropriate. I thought of another approach, setting a flag when a change happened - but this feels very clumsy, since i could have a dozen flags for many different changes.
I have trouble finding out what is going on behind the scenes, probably comes with loose coupling :D

So, is there a concept in artemis that could help me with this, or simply another approach to the issue? Thanks for any replies!

**Comment by RongoMatane** [comment]
Hi, i was quite randomly able to solve this issue. I don't understand why this works, maybe someone has an idea.
The scenario above happened, when i tried to find my new entity with the AspecSubscriptionListener with Aspect.one(EntityComponent.class). I changed it to Aspect.all(EntityComponent.class) and suddenly it works. Does anyone have an idea? The entity does have the component and it can be trieved via the mapper in both cases (it comes with the archetype).

**Comment by piotr-j** [comment]
Both should work exactly the same. If you are not getting inserted/removed callbacks for entities you create, you are doing something wrong. Note that they are not called when you create an entity, but during `world.process()`.

**Comment by RongoMatane** [comment]
Thank you for your reply, this is good to know. So either a bug is present or some sort of side effect that i am not aware of is.
What do is that i call an update function when an entity is inserted or deleted. The entity that is inserted does have the component 'Xcomponent' when the inserted method is called.
With this line:
`IntBag entities = world.getAspectSubscriptionManager().get(Aspect.all(Xcomponent.class)).getEntities();`
all entities including the newly inserted one are retrieved. With this line
`IntBag entities = world.getAspectSubscriptionManager().get(Aspect.one(Xcomponent.class)).getEntities();`
the newly inserted entity is always missed.

I do not understand why this is happening. I'm still happy for any explanation, or would like to help find out where the issue lies, if anyone is interested. I'm using 2.1.0

**Comment by piotr-j** [comment]
Add a listener instead of getting the raw ids. And make a sscce.

**Comment by RongoMatane** [comment]
The issue is this: Aspect.all(ComponentX.class) (apparently) is not equivalent to Aspect.one(ComponentX.class). In my understanding, it should be the same. 

Here you go - i still can't say if i violated a constraint somewhere, or if its a bug in Artemis.
`import com.artemis.Archetype;
import com.artemis.ArchetypeBuilder;
import com.artemis.Aspect;
import com.artemis.BaseSystem;
import com.artemis.Component;
import com.artemis.ComponentMapper;
import com.artemis.EntitySubscription;
import com.artemis.World;
import com.artemis.WorldConfiguration;
import com.artemis.utils.IntBag;

/**
 * Created by Rene on 20.02.2017.
 */
public class Example {

    public static void main(String[] a) {
        WorldConfiguration worldConfiguration = new WorldConfiguration();
        worldConfiguration.setSystem(new ExampleSystem());
        World world = new World(worldConfiguration);

        ExampleSystem exampleSystem = world.getSystem(ExampleSystem.class);

        exampleSystem.currentView.userActionForEntityCreation();
        world.process();

        exampleSystem.currentView.userActionForEntityCreation();
        world.process();
    }

    public static class ExampleSystem extends BaseSystem {

        private View currentView;

        @Override
        protected void initialize() {
            currentView = new View(world);
        }

        @Override
        protected void processSystem() {
        }
    }

    public static class View {

        private final World world;
        private ComponentMapper<ExampleComponent> exampleComponentComponentMapper;
        private Archetype archetype;

        public View(World world) {
            this.world = world;
            exampleComponentComponentMapper = world.getMapper(ExampleComponent.class);
            archetype = new ArchetypeBuilder().add(ExampleComponent.class).build(world);

// The behaviour will be different, whether the next LOC or the line after it is used.
// Although the listener gets called in both cases, subsequent retrievals of entities will only get all entities, if the same aspect was used.
//            Aspect.Builder aspect = Aspect.one(ExampleComponent.class);
            Aspect.Builder aspect = Aspect.all(ExampleComponent.class);
            world.getAspectSubscriptionManager().get(aspect).addSubscriptionListener(new EntitySubscription.SubscriptionListener() {
                @Override
                public void inserted(IntBag entities) {
                    System.out.println("inserted " + entities);
                    for (int i = 0; i < entities.size(); i++) {
                        System.out.println("Entity: " + entities.get(i));
                    }
                    updateViewAfterEntityChange();
                }

                @Override
                public void removed(IntBag entities) {

                }
            });
        }

        public void userActionForEntityCreation() {
            world.create(archetype);
        }

        public void updateViewAfterEntityChange() {
            IntBag entitiesByAll = world.getAspectSubscriptionManager().get(Aspect.all(ExampleComponent.class)).getEntities();
            IntBag entitiesByOne = world.getAspectSubscriptionManager().get(Aspect.one(ExampleComponent.class)).getEntities();
            System.out.println("entitiesByAll = " + entitiesByAll);
            System.out.println("entitiesByOne = " + entitiesByOne);
        }
    }

    public static class ExampleComponent extends Component {
    }
}`

**Comment by piotr-j** [comment]
While they are logically the same, they are not as far as the `world` is concerned. 
By necessity, stuff is updated sequentially and you are hitting a case when its in partial state. I dont think ive used getEntities() outside of a system itself.
Your system should probably subscribe to whatever is needed to update the view and do some in inserted/removed.

**Comment by schosin** [comment]
Why did you decide against using EntitySystem? All you'd have to do is implement ```inserted(Entity)``` and ```removed(Entity)``` and call ```currentView.updateViewAfterEntityChange(getEntities());``` in each.

If you don't want to have the system run every frame, you could also call ```setEnabled(false)``` inside ```initialize```. It would still get notified on entity changes, begin/processSystem/end just wouldn't be called anymore (I actually have a PassiveSystem and PassiveEntitySystem, because I use that quite often).

With a similar setup like yours, just using what I described above, I get the following output:

($anon$1 and $anon$2 are two different entity systems, one with Aspect.all, one with Aspect.one)
> -- Creating world
$anon$1 Initialize, Aspect[all=(MyComponent), one=(), exclude=()]
$anon$2 Initialize, Aspect[all=(), one=(MyComponent), exclude=()]
-- Creating first entity
-- Processing world
$anon$1 Inserted Entity[0]
$anon$2 Inserted Entity[0]
$anon$1 ProcessSystem. getEntities(): Bag(Entity[0])
$anon$2 ProcessSystem. getEntities(): Bag(Entity[0])
-- Creating second entity
-- Processing world
$anon$1 Inserted Entity[1]
$anon$2 Inserted Entity[1]
$anon$1 ProcessSystem. getEntities(): Bag(Entity[0], Entity[1])
$anon$2 ProcessSystem. getEntities(): Bag(Entity[0], Entity[1])
-- Done

Your described behaviour is strange though, but I'd still use EntitySystem anyway.

**Comment by ReneHabermann** [comment]
Thank you for your replies.
@schosin I thought about making my Views extend EntitySystem and thought it was no good fit because 1) the view gets changed a lot, making me add and remove EntitySystems every few seconds and 2) a single Subscription is not sufficient, as a View always deals with different Entity types. As i said i'm not experienced in Artemis or ECS, so i'm not sure if this is sound.
About add/remove the entities on event: When i initially build the screen, i have to use getEntities() of some sort, because there is no change for the listener to react on. So i'd need 2 methods for everything containing entities: buildFromScratch and append/remove, while also adding new logic on how to locate the GUI equivalent of a removed entity. I much prefer the "just build it always from scratch with these entities" approach.

@piotr-j I don't see a nice way to have my view react to deletion or insertion of a single entity. For example, i'll have a table where each entry is a scene 2d actor filled with data of a single entity. If i want to remove a single entity-representing-actor from the table, i'd need to either map it or search it. I'll check if ot comes with other benefits.

The issue was explained, so i'll close it in a few days, if no one objects.
