### ISSUE TITLE
DelayedComponentRemoval has()/get() inconsistency after remove()

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#509]
https://github.com/junkdog/artemis-odb/issues/508#issuecomment-348686357

> Also I've noticed that in removed(int entity) mapper.has() and mapper.get() returns different results. has() would return false (event if annotated with delayed removal), but get() would return the component.

**Comment by ghroot** [comment]
In addition to this, there is also the inconsistency between removing a component from an entity and deleting the entity itself. When a component is removed the mapper will return null (unless marked for delayed removal), and when an entity is deleted all components are available. This is probably how it should be, but still worth a thought. Maybe there should be a separate callback for deleted entities? Not sure.

**Comment by voidburn** [comment]
Maybe the concept of "deleting" an entity should be better described in the
documentation as "scheduling for removal", which makes it clearer that it
will not happen until the following processing iteration.

As for the mappers not to report a removed component, as I said before, is
quite handy in many cases (you might have a system that runs with high
priority that is in charge of removing certain components before other
systems process entities. That should stay as it is IMHO, especially since
you can control that via delayed component removal.

**Comment by junkdog** [comment]
> Maybe the concept of "deleting" an entity should be better described in the
> documentation as "scheduling for removal", which makes it clearer that it
> will not happen until the following processing iteration.

Yeah, it's only mentioned in passing in the javadoc for [EntityTransmuter.java](https://github.com/junkdog/artemis-odb/blob/master/artemis-core/artemis/src/main/java/com/artemis/EntityTransmuter.java#L48).

**Comment by DaanVanYperen** [comment]
Agree this is the desired functionality. Added documentation and tests.
