### ISSUE TITLE
Make prefab file paths a parameter instead of an annotation

### ISSUE THREAD

**Issue by madigan** [junkdog/artemis-odb#510]
Would it be possible to allow prefab file paths to be passed as a parameter at runtime instead of forcing them to be specified in an annotation? Today that forces a Many:1 relationship between Prefab Java class and JSON file. Making that relationship Many:Many would be helpful for the following use cases:

First, suppose I want to have a "Level" Prefab. The only difference between game levels is their content (i.e. the specific entities they contain), and hence in an ideal world the only difference between "Level 1" and "Level 2" would be which .json file gets loaded into the prefab. You could extend this in general to any scenario where the difference between prefabs is contained within the data file itself and instantation remains constant.

Second, suppose I don't know where the file is until runtime. I may have a "Mods" folder that I check first, and then a "default" folder that I fall back to if the file I need is not there.

Another way to look at it is that today the PrefabReader seems to be responsible for both knowing how to locate the resource and how to parse it, and the option of parameterizing the path would allow those functions to be segregated.

Would this enhancement make sense? I could be misunderstanding the tests/API, or there could be some performance or design constraint that led you to it being what it is now, but I figured it wouldn't hurt to ask.

If not, I can create a custom PrefabReader which contains the logic to calculate the filepath based on some external factors, then do the normal JSON parsing.

**Comment by DaanVanYperen** [comment]
The design of prefabs seem to anticipate the future precompile plans (#439). Does the use case of levels apply here? Wonder if it warrants caching.

@junkdog [wiki](https://github.com/junkdog/artemis-odb/wiki/Prefabs) on this topic updated.

**Comment by junkdog** [comment]
It's in part due to #439, but the other use-case is reading the prefab path/id prior to instantiating the class (useful when associated assets need to be loaded, but it's too early to instantiate the prefab).

For loading whole levels/scenes of entities, it' tends to be easier to load it manually (using the `WorldSerializationManager` directly). Prefabs deal more with conceptual entities - like `Player`, `BajoranFreighter`, `UssDefiant` - where some component data need to be updated (e.g. `Position`).

> If not, I can create a custom PrefabReader which contains the logic to calculate the filepath based on some external factors, then do the normal JSON parsing.

Yes, this is the recommended approach. I thought there were some tests covering custom PrefabReaders, but apparently I never got around to writing those.

> Second, suppose I don't know where the file is until runtime. I may have a "Mods" folder that I check first, and then a "default" folder that I fall back to if the file I need is not there.

You can implement your own `FileHandleResolver`, and determine the actual path in `FileHandleResolver::resolve` based on priority/availability.

I used a similar setup at work: in order to keep the android apk slim, we only distributed it with the default content batch - additional content was downloaded in the background, sometime before proceeding to the next area. This way, resources could be read without worrying about where they originated from (classpath, internal or external storage).

> You could extend this in general to any scenario where the difference between prefabs is contained within the data file itself and instantation remains constant.

That would be neat, but not supported atm.

**Comment by DaanVanYperen** [comment]
Spring cleaning stale tickets! Give me a poke if you want this reopened.
