### ISSUE TITLE
Kotlin inaccessable field support

### ISSUE THREAD

**Issue by GregHib** [junkdog/artemis-odb#541]
Artemis fails to access `@EntityId` fields via reflection `ReflectionException: Illegal access to field`, because of the way Kotlin generates getters and setters which leaves the field itself private. See `IntFieldMutator`.

**Comment by HybridEidolon** [comment]
A workaround is to add the `@JvmField` annotation to the property, but I am not certain that will work well if you have explicit get/set definitions.

Not having any experience with artemis, it seems that `com.artemis.utils.reflect.Field` should have an abstraction over getter/setter method pairs in addition to delegating to the `java.lang.reflect.Field` in order to support this use case, and using those if they're present over the field itself. This would make all mutators work on JVM in the general case.

**Comment by DaanVanYperen** [comment]
Added a wiki page to help out Kotlin users. 
https://github.com/junkdog/artemis-odb/wiki/Kotlin

The `@JvmField` workaround should suffice for now, i'm putting this in the freezer as a nice-to-have. If we ever find the time @HybridEidolon solution would be the way to go.
