### ISSUE TITLE
[IMPROVEMENT] Use of Primitive Stacks/Queues

### ISSUE THREAD

**Issue by Speiger** [junkdog/artemis-odb#586]
Hello,

I am working on game and was going to test on Artemis if it was something for my entity system.
But being me I am a person who has to understand everything I use so I am cloning it to make a custom version of it.

On the way I found a couple things that were odd to me.
- Bag allocating 64 entries by default.
- EntityTransmuter requiring a Builder for a single entry (just make a constructor),
- Using 3 steps on things that could be done on a single step. (Mostly for the ComponentType related classes)
- And BitVector not having a fastEquals function even so it would make a lot of sense.

But i found actually something where the performance could be drastically improved.
Your EntitySubscription rebuilds the List of Entities everytime it gets changed.

I was thinking how to solve that issue because this is just such a unnessseary performance loss especially if large systems have many changes. And it really needs just a large amount of entities in 1 system to cause a good performance reduction.

So my idea was: Use Queue/Stack for this system and make use of the bitsets, until a certain point. (Like if 35-40% of the size was removed anyway then just rebuild)

This is the logic I was thinking if there were only small changes made. (Would have to be adjusted based on the state the system is in)
```java
Int2IntMap map = new Int2IntOpenHashMap();
IntArrayList list = new IntArrayList();
IntPriorityQueue queue = new IntArrayPriorityQueue();
DynamicBitSet presentEntities = new DynamicBitSet(); // BitVector

public void process(IntList insertions, IntList removals)
{
	//Simulating here changes were already decided to be added & removed
	for(int i = 0, s = removals.size();i<s;i++)
	{
		int id = removals.get(i);
		if(presentEntities.getFast(id))
		{
			remove(id);
		}
	}
	for(int i = 0, s = insertions.size();i<s;i++)
	{
		int id = insertions.get(i);
		if(presentEntities.getFast(id))
		{
			continue;
		}
		insert(id);
	}
	clearEmptyHoles();
}

private void clearEmptyHoles()
{
	//Queue size is just a getter so faster then making a !(size == 0)
	while(queue.size() > 0)
	{
		int nextSlot = queue.dequeueInt();
		if(nextSlot == list.size()) // Last slot is empty so we need to clear it from the Entities too and clear the queue
		{
			list.pop();
			queue.clear();
			return;
		}
		else if(nextSlot > list.size()) // Slot is bigger then the largest index of the list meaning its already of the list and auto cleared.
		{
			queue.clear();
			return;
		}
		int id = list.popInt();
		while(id == 0 && nextSlot <= list.size()) // Finding the next none empty object
		{
			id = list.popInt();
		}
		if(nextSlot > list.size())
		{
			return;
		}
		map.put(id, nextSlot);
		list.set(nextSlot, id);
	}
}

public void remove(int id)
{
	presentEntities.clearFast(id);
	int index = map.remove(id);
	queue.enqueueInt(index);
	list.set(index, 0);
}

public void insert(int id)
{
	presentEntities.setFast(id);
	if(queue.size() > 0)
	{
		int index = queue.dequeueInt();
		list.set(index, id);
		map.put(id, index);
		return;
	}
	map.put(id, list.size());
	list.add(id);
}
```

This system would allow not to "Constantly on any change" to rebuild the Iteration queue
while using a tiny bit more memory. This is only a proof of concept but if having enough large systems would maybe have a performance improvement. 

Oh yeah I know I used "FastUtil" and thats not used because its class count is so big but its just there to provide a point of what my idea is.

Edit: My game will be most likely pc only and I know android is a bit different in performance, but that is what I have thought of while building my own system of this implementation, maybe it will help.

**Comment by Speiger** [comment]
Ok after reading over things, This could work for tiny changes, the other option would be to iterate over the bitset instead of a list. This would make a performance improvement if the list changes per update logic 
And even if it is a tiny bit slower compared to a list iterator, on a larger scale system with loads of changes it could improve the speed. (Assuming the set is single threaded)

**Comment by junkdog** [comment]
> * Bag allocating 64 entries by default.

Ah, good catch! Yeah, should probably be fixed (and update some call sites).

> * And BitVector not having a fastEquals function even so it would make a lot of sense.

What is `fastEquals`?

> * EntityTransmuter requiring a Builder for a single entry (just make a constructor),

Hmm, transmuters are rarely used for toggling a single component type - component mappers already wrap a transmuter for add/create/remove. What are your use-cases? Aspect.Builder is otherwise a simple `all(ComponentA.class)` vs `ComponentA.class`.

> So my idea was: Use Queue/Stack for this system and make use of the bitsets, until a certain point. (Like if 35-40% of the size was removed anyway then just rebuild)

Pretty neat. I experimented a bit with similar ideas, never did any proper implementation however. Entity removal was a real bottleneck in early artemis versions. The current solution certainly makes the presumably cheap scenario somewhat more expensive, but highly fluctuating entity systems are relatively cheap to update.

One feature of the current implementation is that entities are always passed as sorted `Entity<Bag>` or `IntBag`; this improves iteration speed (presumably from better cache-locality over component arrays), and also guarantees that systems process a sorted set of entities; some systems depend on this behavior alt can make use of it, eg renderers.

> Ok after reading over things, This could work for tiny changes, the other option would be to iterate over the bitset instead of a list.

iterate over `presentEntities`? It's considerably slower than iterating over an `int[]`; the cost of translating the bits over to `list` is likely recouped on tick 2, maybe 3.

**Comment by Speiger** [comment]
Other thing:
The class name "World" is really picked for the "EntityComponentSystem".
Because some could just use it for "Entities" in their "World.class" which would mean they would have to implement a wrapper just to use your ECS Library (Also a reason why I manually copy it)
My suggestion would be to either name the main class that you should use: "EntityComponentSystem" or "ECSWorld"
So you have still a good indicator but do not try to conflict with other projects that actually want to use your Library.

**Comment by junkdog** [comment]
> Here you could use a fastEquals where you remove all the "class type validations" and have a equals function that requires a BitVector instead of a Object.

Hmm, not sure it would make a measurable difference, but could be interesting to test next time when running the benchmarks. The bitsets are rarely compared by equality; only when transmuting to a new composition id or when a new composition id is allocated.

> Yeah but if every update the system changes that would mean you have 1 system that has 1 slow iteration (Your BitVector Iteration) and 1 fast iteration. Then it would make sense to iterate only over the BitSet/BitVector since you do that anyways and the second iteration would make no sense.

EntitySubscriptions are decoupled from the system, so there is no way to process the entity system at the same time as repopulating the IntBag-of-entities. Aspect:s with the same configuration share the same EntitySubscription instance, so the same entity list can be shared between multiple systems.

> 1 large scale system that constantly changes would be enough to cripple performance enough to notice it. (5k-50k range of entities)

On desktop, depends on what you do of course, but artemis' overhead from mutating multiple systems in a 50k entities world shouldn't be a problem - at high entity counts, the workload to process highly populated systems is a bigger issue. I occasionally do small stress-test projects - [100k entities](https://www.youtube.com/watch?v=Dtn671JpXrU), spawning 35k entities/s. Earlier screenshot showing [systems](https://twitter.com/junkdogAP/status/757531123845038080).

The [benchmarks for 65k entites](https://github.com/junkdog/entity-system-benchmarks#benchmarks-65536-entites) might be interesting too.

> The class name "World" is a really bad picked name for the "EntityComponentSystem".

It's been called `World` since 2011 or so, before artemis-odb existed. Don't recall which libraries also call their "thing" `World`, but I've ran into it a couple of times. So, might indeed be better names out there, but changing it means invalidating a lot of existing online resources.

> "World.class" which would mean they would have to implement a wrapper just to use your ECS Library (Also a reason why I manually copy it)

Sure, typing `com.artemis.World` is longer than `World`, but I don't see the need for a wrapper(?).

**Comment by Speiger** [comment]
>Hmm, not sure it would make a measurable difference, but could be interesting to test next time when running the benchmarks. The bitsets are rarely compared by equality; only when transmuting to a new composition id or when a new composition id is allocated.

Well it might be a tiny bit faster but will make barely any difference but since you already have functions that do exactly the same thing. Its more of a keep a consistency thing.

> EntitySubscriptions are decoupled from the system, so there is no way to process the entity system at the same time as repopulating the IntBag-of-entities. Aspect:s with the same configuration share the same EntitySubscription instance, so the same entity list can be shared between multiple systems.

Yeah I am aware of that part but for me it seems weird if 2 systems use the same subscription and also same entities.
But my idea is to have a Acceptor in it that it just dumps into when requesting the entities. Since you would just remove the entire iteration of the list if the system is changing a lot. So that would get rid of 1 entire step. (IntConsumer FYI)
Maybe as a Optional way on highly changing systems that change every time the getEntities are called.

> On desktop, depends on what you do of course, but artemis' overhead from mutating multiple systems in a 50k entities world shouldn't be a problem - at high entity counts, the workload to process highly populated systems is a bigger issue. I occasionally do small stress-test projects - 100k entities, spawning 35k entities/s. Earlier screenshot showing systems.
The benchmarks for 65k entites might be interesting too.

Yes ofcourse. Entity processing will be the larger issue. The idea behind that is "Processing gets more time and the gatherer is optimized so it can not cause any issues". Maybe not the best idea but thats just me

> It's been called World since 2011 or so, before artemis-odb existed. Don't recall which libraries also call their "thing" World, but I've ran into it a couple of times. So, might indeed be better names out there, but changing it means invalidating a lot of existing online resources. 
> Sure, typing com.artemis.World is longer than World, but I don't see the need for a wrapper(?).

Yeah Might be called but what if you write a custom engine and call it your world also world? Because its more fitting then anything else? And you use this library just for entities. Then World makes no sense for this kind of library (ofc always context sensitive). 
Ofcourse changing it after a long time would break a lot of things.
Also thats just me but I hate manual Imports and avoid them as much as possible. (I rather manually clone a giant library then having a manual import if it is frequently happening)
Also it causes only confusion when you are allowing other people to use your code. Because you always have to look: Is it now world or is it the EntityWorld. Etc Etc Etc.
But again thats just me.
(And yes I know a lot of custom engines use the "World.class" because it makes sense to use something that represent a World as a "World.class", What else would you use? (Could be used in this libraries case too FYI))

**Comment by Speiger** [comment]
FYI I can rename the World myself. Its just me that wants to point that out ^^" So no worry there.

**Comment by DaanVanYperen** [comment]
Multi-topic tickets tend to be non-actionable so I've elevated the topics that we might pursue to separate tickets. Up to @junkdog if he wants to elevate more. Closing for now!

**Comment by Speiger** [comment]
Yeah fine by me.
