### ISSUE TITLE
[Question] Entity limit ?

### ISSUE THREAD

**Issue by genaray** [junkdog/artemis-odb#600]
How many entities can exist in one artemis world ? Is there a limit ? Or someway to extend that limit ?

**Comment by junkdog** [comment]
artemis is single-threaded, so you're effectively limited by how fast all systems are processed. It's hard to put a number to the max entity count as the majority of processing time won't be due to artemis; with simple or sparsely populates systems, entity count can naturally go higher than in more complex simulations.
