### ISSUE TITLE
[BUG] @PooledWeaver rewrites base class, breaking components at runtime

### ISSUE THREAD

**Issue by schosin** [junkdog/artemis-odb#604]
Using `@PooledWeaver` rewrites the annotated components base class to `PooledComponent`.
This causes errors at runtime if the base class wasn't `Component`.

Weaver should ignore components not extending `Component` directly and just log a warn or mark it as "NOT_OPTIMIZABLE" similar to system optimization.

On a side note, would it be an option to use an interface for the pooling logic and have `PooledComponent` implement it? Unless someone uses `ComponentPool` directly, it shouldn't break too much.

On another side note, `@PooledWeaver` also breaks on encountering arrays. Adding a float[] to ComponentToWeave breaks a test in artemis-weaver. I don't really want to spam issues, although this is a seperate issue. 
The problem here is the sort of instance fields "so that RW operations are type aligned".

**Comment by DaanVanYperen** [comment]
:cookie: @schosin

> Weaver should ignore components not extending Component directly and just log a warn or mark it as "NOT_OPTIMIZABLE" similar to system optimization.

Went the fail fast route (RuntimeException during weaving) as it is incorrect use of the annotation..

> On another side note, @PooledWeaver also breaks on encountering arrays. Adding a float[] to ComponentToWeave breaks a test in artemis-weaver. I don't really want to spam issues, although this is a seperate issue.
The problem here is the sort of instance fields "so that RW operations are type aligned".

I've fixed the breakage. @junkdog can take a look at the RW optimization for arrays, it is beyond me.  Have not tested if pooled objects with arrays cause issues elsewhere.
