### ISSUE TITLE
[Question] how is the compent managed in memory?

### ISSUE THREAD

**Issue by choxsword** [junkdog/artemis-odb#608]
the reason ECS (entity component system) has great performance, like entitas in unity, is that components of same type are put in the same memory chunk, which make component iterating fast and efficient.

However, in java we cannot manage object memory location, so ecs seems to be not so useful as c++ in java language. Does this frameworkd handled this problem?

**Comment by genaray** [comment]
Good question... thats something i wanna know too

**Comment by exuvo** [comment]
Memory layout wise the best we can do in java is allocate a lot of same type components at the same time and hope they get allocated close to each other. You can be pretty certain they will be stored in allocation order at least. Artemis supports pooling (reuse) of components so this works. But javas object overhead is always there even if they are stored consecutively so cache usage is always worse than in C++. Future javas inline types might solve it but i am doubtful as they for some reason went with immutable only which is a bad fit for games.

Cache usage will still be better than single massive classes as the individual components are smaller and the prefetcher actually has a chance to prefetch the next component instead of more of the same class instance data assuming they were stored near each other. Do note that all object variables in java are pointers to the heap so try to use raw types like ints as much as possible as those are actually stored where you want.

If you really need maximum performance stick to c++.
